// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejetazqddcwlyoyfhvhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqZXRhenFkZGN3bHlveWZodmhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTEzMzMsImV4cCI6MjA3MTE2NzMzM30.H3YjwtW7G_71i8MilixlnkOW5Vo9hYU-JDDOfs1tOsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});